name: Deploy Website

on:
  push:
    branches:
      - main  # Beachte, dass der Hauptbranch "main" genannt wird

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Website
      run: |
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Passe dies an den Pfad deines Build-Verzeichnisses an
        cname: LeonRothauer.github.io  # Füge dies hinzu, wenn du eine eigene Domain verwenden möchtest
